In [166]:
import ChainCRF
import importlib
importlib.reload(ChainCRF)
from ChainCRF import ChainCRF
import torch
import torch.nn as nn
import torch.nn.functional as F

In [167]:
batch_size = 1
seq_len = 4
num_class = 3
# 预定义的列表
init_Trans = [[1, 0, 2],
              [2, 0, 3],
              [1, 9, 0]]
my_crf = ChainCRF(num_class, init_Trans)
my_crf = ChainCRF(num_class)

init_emission = [[[0.0, 1.5, 3.0],
                  [0.5, 1.0, 3.0],
                  [0.5, 0.0, 0.0],
                  [1.0, 1.0, 1.0],]]
init_emission = torch.rand((batch_size,seq_len,num_class))
# 使用列表初始化1 4 3
emissions = torch.tensor(init_emission)
# 1 4
init_tags = [[2, 1, 2, 1]]
true_tags = torch.Tensor(init_tags)

init_masks = [[1, 1, 1, 0]]
mask = torch.Tensor(init_masks)

print(my_crf.viterbi_decode(emissions, mask))
print(my_crf.viterbi_decode2(emissions, mask))
# tensor([[2, 1, 2, 0]])


score: tensor([[[ 0.0000,  1.5000,  3.0000],
         [ 4.5000, 13.0000,  7.5000],
         [15.5000, 16.5000, 16.0000],
         [19.5000, 26.0000, 20.5000]]], grad_fn=<CopySlices>)
path: tensor([[[0, 0, 0],
         [2, 2, 1],
         [1, 2, 1],
         [1, 2, 1]]])
tensor([[2, 1, 2, 0]])
score: tensor([[[ 0.0000,  1.5000,  3.0000],
         [ 4.5000, 13.0000,  7.5000],
         [15.5000, 16.5000, 16.0000],
         [19.5000, 26.0000, 20.5000]]], grad_fn=<CopySlices>)
path: tensor([[[0, 0, 0],
         [2, 2, 1],
         [1, 2, 1],
         [1, 2, 1]]])
tensor([[2, 1, 2, 0]])


In [168]:
my_crf(emissions,true_tags.long(),mask)

tensor(7.1004, grad_fn=<MeanBackward0>)