In [6]:
import torch
def aa(lll):
    b = torch.Tensor(lll).unsqueeze(1)
    return torch.logsumexp(b,dim=0)

In [7]:
list = [1.5,4,4.5]

aa(list)

tensor([5.0046])

In [8]:
list = [1.5000,  1.0000,  5.0000]

aa(list)

tensor([5.0474])

In [9]:
list = [1,  2.5, 13]

aa(list)

tensor([13.0000])

In [10]:
list = [5,  7.5, 6]

aa(list)

tensor([7.7664])